## 1. Write a Python Program to find sum of array?

In [44]:
import numpy as np
sum=0
arr1 = np.array([1, 2, 3, 4, 5, 6])
np.sum(arr1)

21

## 2. Write a Python Program to find largest element in an array?

In [45]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.max(arr))

6


## 3. Write a Python Program for array rotation?

import numpy as np
arr2=np.ndarray((2,2))
print(arr2)
np.rot90(arr2)

## 4. Write a Python Program to Split the array and add the first part to the end?

In [79]:
import numpy as np
arr3=np.array([1, 2, 3, 4, 5, 6])
print(arr3)
sarray = np.array_split(arr3,2)
np.append(sarray[1],sarray[0])

[1 2 3 4 5 6]


array([4, 5, 6, 1, 2, 3])

## 5.5. Write a Python Program to check if given array is Monotonic?

In [102]:
import numpy as np
arr = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
np.digitize(arr,bins,right=False)

array([1, 4, 3, 2], dtype=int64)