## 1. Write a Python Program to Add Two Matrices?

In [20]:
import numpy as np

def add_mat(mat1,mat2):
    try:
        add = mat1 + mat2
        print("matrix 1 is\n {}".format(mat1))
        print("matrix 2 is\n {}".format(mat2))
        print(add)
    except exceptions as e:
        print(e)
mat1 = np.ndarray((3,3),dtype = int)
mat2 = np.ndarray((3,3),dtype = int)
add_mat(mat1,mat2)


matrix 1 is
 [[ 93876440644572               0 140038331818048]
 [140038331820352 140038331821888 140038331820448]
 [140038331819968 140038331819728              80]]
matrix 2 is
 [[ 93876430980402               0 140038331819536]
 [140038331821024 140038331818336 140038331821936]
 [140038331821312 140038331818240              80]]
[[187752871624974               0 280076663637584]
 [280076663641376 280076663640224 280076663642384]
 [280076663641280 280076663637968             160]]


## 2. Write a Python Program to Multiply Two Matrices?

In [24]:
import numpy as np

def mat_mul(mat1,mat2):
    try:
        res = np.matmul(mat1,mat2)
        print(res)
    except exceptions as e:
        print(e)
mat1 = np.array(([3,2,1],[4,5,2],[6,7,3]),dtype = int)
mat2 = np.array(([1,2,9],[3,4,5],[5,6,3]),dtype = int)
mat_mul(mat1,mat2)


[[14 20 40]
 [29 40 67]
 [42 58 98]]


## 3. Write a Python Program to Transpose a Matrix?

In [30]:
import numpy as np

def mat_trs(mat):
    try:
        print("Before Transpose\n {}".format(mat))
        res = np.transpose(mat)
        print("\n After Transpose \n {}".format(res))
    except exceptions as e:
        print(e)
mat = np.array(([3,2,1],[4,5,2],[6,7,3]),dtype = int)
mat_trs(mat)

Before Transpose
 [[3 2 1]
 [4 5 2]
 [6 7 3]]

 After Transpose 
 [[3 4 6]
 [2 5 7]
 [1 2 3]]


## 4. Write a Python Program to Sort Words in Alphabetic Order?

In [30]:
import numpy  as np
def word_sort(sent):
    try:
        print("Original\n  {}".format(sent))
        res = sent.split()
        temp = np.sort(res)
        mod = ' '.join(temp)
        print("In Alpahbetical order\n {}".format(mod))
    except exceptions as e:
        print(e)
string = "My name is Arun and i like Data"
word_sort(string)

Original
  My name is Arun and i like Data
In Alpahbetical order
 Arun Data My and i is like name


## 5. Write a Python Program to Remove Punctuation From a String?

In [41]:
def rem_punc(sent):
    try:
        print("Before\n  {}".format(sent))
        punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
        for ele in sent:
            if ele in punc:
                sent = sent.replace(ele,'')
        print("After\n {}".format(sent))
    except exceptions as e:
        print(e)
sent = "My name is Arun and, i like Data!?"
rem_punc(sent)

Before
  My name is Arun and, i like Data!?
After
 My name is Arun and i like Data
